### ISSUE TITLE
Error while trying to get the module

### ISSUE THREAD

**Issue by iresharma** [resendlabs/resend-go#25]
Hello, I am relatively new to golang.
I was trying to use resend SDK it threw the following error when trying to install.

```go
go: downloading github.com/resend/resend-go v1.7.0
go: github.com/resend/resend-go@v1.7.0: parsing go.mod:
        module declares its path as: github.com/resendlabs/resend-go
                but was required as: github.com/resend/resend-go
```

**Comment by drish** [comment]
hey @iresharma thanks for reporting the issue, looks like our docs were released a bit earlier than the paths renaming on our sdk, we're releasing a new version soon that fixes the issue.
In the meanwhile, installing via: `go get github.com/resendlabs/resend-go` should work, closing the issue here, but feel free to re-open if you still have issues.

**Comment by drish** [comment]
@iresharma just wanted to let you know that v2.3.0 has just been released with the fix for installing through the new github handle

```
root@e84f4de01f1c:~# go get github.com/resend/resend-go/v2
go: downloading github.com/resend/resend-go v1.7.0
go: downloading github.com/resend/resend-go/v2 v2.3.0
go: added github.com/resend/resend-go/v2 v2.3.0
```

**Comment by iresharma** [comment]
Thank you for informing
